;;;; cl-alphastrike.lisp

(in-package #:cl-alphastrike)

(defun display-record-sheet (element)
  (let ((name      (make-instance 'label :text (name element)))
        (pv        (make-instance 'label :text (pv element)))
        (kind      (make-instance 'label :text (kind element)))
        (size      (make-instance 'label :text (size element)))
        (tmm       (make-instance 'label :text (tmm element)))
        (move      (make-instance 'label :text (format nil "~A~A" (mv element) (mv-type element))))
        (role      (make-instance 'label :text (role element)))
        (skill     (make-instance 'label :text (skill element)))
        (damage    (make-instance 'label :text (format nil "~A" (damage element))))
        (ov        (make-instance 'label :text (overheat element)))
        (heat      (make-instance 'label :text (heat element)))
        (armor     (make-instance 'label :text (format nil "~A/~A" (current-armor element) (armor element))))
        (structure (make-instance 'label :text (format nil "~A/~A" (current-structure element) (structure element))))
        (specials  (make-instance 'label :text (format nil "~A" (specials element))))
        (crits     (make-instance 'label :text (format nil "~A" (crits element)))))
    ((grid name 0 0)
     (grid pv 1 0)
     (grid kind 0 1)
     (grid size 1 1)
     (grid tmm 2 1)
     (grid move 3 1)
     (grid role 0 2)
     (grid skill 2 2)
     (grid damage 0 3)
     (grid ov 0 4)
     (grid heat 1 4)
     (grid armor 0 5)
     (grid structure 0 6)
     (grid specials 0 7)
     (grid crits 0 8))))

(defun main ()
  (with-ltk ()
    (display-record-sheet (locust-lct-1v))))
